### ISSUE TITLE
Pong, but it uses our library

### ISSUE THREAD

**Issue by novialriptide** [pygame-community/pygame-geometry#116]
One of the most popular starting pygame projects is Pong, but many people use `pygame.Rect` for its collisions. To demonstrate our library in the most simplest way possible, I propose creating a Pong example after we have finalized our API design.

I would also like to create new coding conventions for future examples so they can all stay consistent.

**Comment by novialriptide** [comment]
Adding a `type:wontfix` tag since our API design is not finalized yet.

**Comment by itzpr3d4t0r** [comment]
Closing this as we now have the pong example.
